language: node_js
node_js:
  - 12
  - 14
  - 15
services:
  - postgresql
before_script:
  - psql -f application/db/install.sql -U postgres
  - PGPASSWORD=nolik psql -d wave -f application/db/structure.sql -U nolik
  - PGPASSWORD=nolik psql -d wave -f application/db/data.sql -U nolik
script:
  - npm test
